jwt:
  secret: javainuse
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: 456123
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop