# Spring boot application
spring:
  application:
    name: luzhou-service-content-consumer
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 7779
  servlet:
    context-path: /content
# Services Versions
services:
  versions:
    content:
      v1: 1.0.0

# Dubbo Config properties
dubbo:
  scan:
    basePackages: com.antsdouble.luzhou.service.content.consumer
  ## ApplicationConfig Bean
  application:
    id: luzhou-service-content-consumer
    name: luzhou-service-content-consumer
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 30882
    status: server
    serialization: kryo

  ## RegistryConfig Bean
  ##     address: zookeeper://192.168.10.131:2181?backup=192.168.10.131:2182,192.168.10.131:2183
  registry:
    id: zookeeper
    address: zookeeper://192.168.15.13:2182

# Dubbo Endpoint (default status is disable)
endpoints:
  dubbo:
    enabled: true

management:
  server:
    port: 8889
  # Dubbo Health
  health:
    dubbo:
      status:
        ## StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
  # Enables Dubbo All Endpoints
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.antsdouble.luzhou: debug
  file:
    path: ./contentconsumer.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
